# Generated by Django 3.1 on 2020-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0004_auto_20201021_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
