# Generated by Django 3.1 on 2020-10-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='socialmediasettings',
            old_name='Youtube',
            new_name='youtube',
        ),
    ]
